spring.application.name=santiagoweb                  
spring.datasource.url= jdbc:postgresql://localhost:5432/backend_db
spring.datasource.username= backend_user
spring.datasource.password= backend_password
spring.datasource.driver-class-name=org.postgresql.Driver